typography_spectrum: 0.1379928
color:
  saturation: 0.5017921
  brandStrength: 0.4892473
  lightness: 0.4749104
  brandColors:
    - '#C4CBDD'
    - '#5C554D'
    - '#7C7F84'
    - '#08090E'
    - '#FCFFFF'
  rhythmicContrast: 0.4892473
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7921147
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Sebastien Arbour
  email: Arbour@ArbourPhoto.com
  url: www.ArbourPhoto.com
name: Arbour Construction Images
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Arbour Photographe 450.961.7815  Arbour@ArbourPhoto.com
purpose: []
